# Домашнє завдання до теми "Розширені методи обробки даних у Pandas"

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df=pd.read_csv('drive/MyDrive/supermarket_sales.csv')

1. Відсортуйте дані за спаданням ціни товара ('Unit price') і виведіть 5 перших рядочків на екран.

In [4]:
df.sort_values(by="Unit price", ascending=False).head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.986,734.706,1/23/2019,10:33,Cash,699.72,4.761905,34.986,6.1
122,219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.982,944.622,3/9/2019,17:26,Credit card,899.64,4.761905,44.982,4.2
930,641-62-7288,B,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.976,629.496,3/24/2019,13:33,Ewallet,599.52,4.761905,29.976,7.1
494,437-53-3084,B,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.989,209.769,2/26/2019,11:48,Ewallet,199.78,4.761905,9.989,7.1
283,667-92-0055,A,Yangon,Member,Male,Health and beauty,99.83,6,29.949,628.929,3/4/2019,15:02,Ewallet,598.98,4.761905,29.949,8.5

2. Знайдіть інвойс (рядок в даних) в категорії товарів `Electronic accessories`, в якому був куплений товар з найбільшою кількістю і найбільшою ціною. Виведіть цей рядок даних на екран.

In [9]:
electronic_df = df[df["Product line"] == "Electronic accessories"]
electronic_df.sort_values(["Quantity", "Unit price"], ascending=False).head(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
105,704-48-3927,A,Yangon,Member,Male,Electronic accessories,88.67,10,44.335,931.035,1/12/2019,14:50,Ewallet,886.7,4.761905,44.335,7.3

3.1. Створіть нову колонку в даних `Rating Category`, яка визначає категорію рейтингу (`Rating`): високий, середній чи низький за наступним правилом:
- якщо рейтинг вищий або рівний 8 - то він високий (`High`)
- якщо рейтинг від 6 (включно) до 8 (не включно) - то він середній (`Medium`)
- інакше - низький (`Low`).

In [10]:
def rating_category(rating):
    if rating >= 8:
        return "High"
    elif rating >= 6:
        return "Medium"
    else:
        return "Low"

df["Rating Category"] = df["Rating"].apply(rating_category)

print(df[["Rating", "Rating Category"]].head())

   Rating Rating Category
0     9.1            High
1     9.6            High
2     7.4          Medium
3     8.4            High
4     5.3             Low

3.2. Виведіть, який відсоток даних становить кожне зі значень категорій рейтингу.

In [11]:
print((df["Rating Category"].value_counts(normalize=True) * 100).round(2))

Rating Category
Medium    35.6
High      32.9
Low       31.5
Name: proportion, dtype: float64

4.1. Запустіть код нижче аби створити змінну `time`. Ця змінна містить час в форматі "година:хвилина". Напишіть функцію `get_hour`, яка буде зі змінної формату як `time` дістати лише години і конвертувати їх у тип `int`.

Запустіть написану функцію на змінній `time` та перевірте правильність роботи функції.

In [12]:
time = '11:28'

In [13]:
def get_hour(time):
    hour = time.split(":")[0]
    return int(hour)

print(get_hour(time))

11

4.2. З допомогою функції `get_hour` і метода `DataFrame.apply()` створіть нову колонку `Hour` в нашому наборі даних, яка буде містити години здійснення покупки, обчислені на основі часу здійснення покупки `Time`.

In [14]:
df["Hour"] = df["Time"].apply(get_hour)

print(df[["Time", "Hour"]].head())

    Time  Hour
0  13:08    13
1  10:29    10
2  13:23    13
3  20:33    20
4  10:37    10

4.3. Виведіть кількість значень за кожною годиною покупки і дайте відповідь "О яких годинах найбільше здійснюють покупок покупці і чому на Ваш погляд саме о цих годинах? Чи це слогічно, що найбільше покупок саме в ці години?".

In [15]:
print(df["Hour"].value_counts().sort_index())

Hour
10    101
11     90
12     89
13    103
14     83
15    102
16     77
17     74
18     93
19    113
20     75
Name: count, dtype: int64

Найбільше покупок здійснюють о 19:00. На мою думку, це логічно, оскільки в цей час люди зазвичай закінчують роботу або навчання та можуть заходити до супермаркету, щоб придбати продукти додому. Також увечері люди мають більше вільного часу для покупок. Тому те, що найбільше покупок припадає на вечірні години, виглядає цілком логічно

5. Виведіть середнє значення чеку (`Total`) для покупок в містах, наявних в даних, за допомогою функції `groupby`.

In [16]:
print(df.groupby("City")["Total"].mean().round(2))

City
Mandalay     319.87
Naypyitaw    337.10
Yangon       312.35
Name: Total, dtype: float64

6. Виведіть кількість покупок, середнє, мінімальне та максимальне значення для загальної суми чеку (Total) в містах, наявних в даних, за допомогою функції groupby.
Зробіть висновки з цих показників та дайте рекомендації для мережі супермаркетів.

In [17]:
result = df.groupby("City")["Total"].agg(
    Кількість_покупок="count",
    Середній_чек="mean",
    Мінімальний_чек="min",
    Максимальний_чек="max"
)

print(result.round(2))

           Кількість_покупок  Середній_чек  Мінімальний_чек  Максимальний_чек
City
Mandalay                 332        319.87            18.64           1022.49
Naypyitaw                328        337.10            10.68           1042.65
Yangon                   340        312.35            12.69           1039.29

За результатами аналізу можна порівняти міста за кількістю покупок, середнім, мінімальним та максимальним чеком. Кількість покупок показує, у яких містах більше клієнтів. Середній чек допомагає визначити, де покупці витрачають більше грошей за одну покупку. Мінімальний і максимальний чеки показують діапазон сум покупок.
Для збільшення прибутку варто звернути увагу на міста з нижчим середнім чеком і спробувати збільшити суму покупки за допомогою акцій «2 за ціною 1», знижок при купівлі декількох товарів та рекомендацій супутніх товарів. У містах із високим середнім чеком доцільно підтримувати асортимент популярних товарів і заохочувати повторні покупки

7. Ми внесли деякі зміни в наш набір даних, тож, давайте запишемо результат у файл. Запишіть оновлену версію даних у файл `supermarket_sales_enriched.csv`. Зверніть увагу, аби не записати нічого зайвого, наприклад, індекси рядків нам в файлі не потрібні, оскільки вони стандартні.

In [18]:
df.to_csv("supermarket_sales_enriched.csv", index=False)