#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df=pd.read_csv('drive/MyDrive/supermarket_sales.csv')

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [3]:
profit_by_branch = df.groupby("Branch")["gross income"].sum()

print(profit_by_branch)

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [4]:
branch_profit = df.groupby(["Branch", "City"])["gross income"].sum()

print(branch_profit.sort_values(ascending=False).head(1))

Branch  City
C       Naypyitaw    5265.1765
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [7]:
invoices_by_category = pd.crosstab(df["Branch"], df["Product line"])

invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [8]:
print(invoices_by_category["Electronic accessories"].idxmax())

A

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. Чоловіки та жінки можуть мати різні вподобання щодо категорій товарів.

In [12]:
gender_product = pd.crosstab(df["Gender"], df["Product line"])

gender_product

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,84,96,90,64,79,88
Male,86,82,84,88,81,78

Жінки найчастіше купують Fashion accessories — 96 покупок. Чоловіки найчастіше купують Health and beauty — 88 покупок. Найменше жінки купують Health and beauty — 64 покупки, а чоловіки — Sports and travel — 78 покупок.
Бізнес-рішення: можна створювати різні акції та рекламні пропозиції для чоловіків і жінок, орієнтуючись на категорії, які вони купують найчастіше.

2. Покупці можуть надавати перевагу певному способу оплати.

In [14]:
payment_counts = df["Payment"].value_counts()

payment_counts

Payment
Ewallet        345
Cash           344
Credit card    311
Name: count, dtype: int64

Найчастіше покупці оплачують покупки через E-wallet — 345 інвойсів. Майже стільки ж покупок оплачено готівкою — 344, а Credit card — 311.
Бізнес-рішення: варто забезпечити стабільну роботу електронних гаманців і заохочувати їх використання, наприклад бонусами або знижками. Це може зробити процес оплати швидшим і зручнішим для покупців.

3. Покупці можуть оцінювати різні категорії товарів по-різному

In [16]:
rating_by_product = df.groupby("Product line")["Rating"].mean().sort_values(ascending=False)

rating_by_product.round(2)

Product line
Food and beverages        7.11
Fashion accessories       7.03
Health and beauty         7.00
Electronic accessories    6.92
Sports and travel         6.92
Home and lifestyle        6.84
Name: Rating, dtype: float64

Найвищий середній рейтинг мають Food and beverages — 7.11, а найнижчий — Home and lifestyle — 6.84.
Бізнес-рішення: Варто підтримувати якість товарів у категоріях із високим рейтингом, а для категорій із нижчим рейтингом дослідити причини невдоволення покупців та покращити асортимент або якість товарів